#!/bin/bash
# Quick Gemini API Key Setup - Interactive Helper

echo "🚀 GEMINI API KEY SETUP - INTERACTIVE HELPER"
echo "============================================="
echo ""

echo "📋 STEP 1: Get Your FREE API Key"
echo "--------------------------------"
echo "1. Open this link in your browser:"
echo "   👉 https://makersuite.google.com/app/apikey"
echo ""
echo "2. Sign in with your Google account"
echo ""
echo "3. Click the blue 'Create API key' button"
echo ""
echo "4. Copy the entire key (it looks like: AIzaSyC-xxxxxxxxxxxxxxxxx)"
echo ""

echo "📋 STEP 2: Set Your API Key"
echo "----------------------------"
echo "Once you have your key, run this command:"
echo ""
echo "export GEMINI_API_KEY=\"paste_your_key_here\""
echo ""
echo "Replace 'paste_your_key_here' with your actual API key!"
echo ""

echo "📋 STEP 3: Test Your Setup"
echo "---------------------------"
echo "After setting your key, test it with:"
echo ""
echo "python3 scripts/check_api_keys.py"
echo ""

echo "📋 STEP 4: Start Your AI Employee"
echo "----------------------------------"
echo "Once your key is working, start your system:"
echo ""
echo "python3 orchestrator.py --vault ./vault --live"
echo ""

echo "🎯 WHAT YOU'LL GET:"
echo "==================="
echo "✅ FREE tier: 1,500 requests per day"
echo "✅ Full Claude Code functionality"
echo "✅ All tools: bash, read, write, web_search, playwright"
echo "✅ All MCP servers: email, social, linkedin, twitter"
echo "✅ All skills: /process-emails, /pdf, /browsing-with-playwright"
echo "✅ Automatic email processing"
echo "✅ Document analysis and response"
echo "✅ Enterprise-grade fallback system"
echo ""

echo "💡 NEED HELP?"
echo "=============="
echo "If you get stuck:"
echo "1. Make sure you copied the ENTIRE API key"
echo "2. Make sure there are no extra spaces"
echo "3. The key should start with 'AIza'"
echo "4. Run: echo \$GEMINI_API_KEY to verify it's set"
echo ""

echo "🚀 Ready to get your API key? Go to:"
echo "👉 https://makersuite.google.com/app/apikey"