#!/bin/bash
# Cron Job Setup for Personal AI Employee
#
# This script sets up scheduled tasks for:
# - Process Needs_Action every 5 minutes (main automation loop)
# - Daily morning briefing (8:00 AM)
# - Weekly CEO briefing (Monday 7:00 AM)
# - Hourly health check
#
# Usage: ./scripts/setup_cron.sh [--remove] [--dry-run]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Personal AI Employee - Cron Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Dry-run mode
DRY_RUN=false
if [ "$1" == "--dry-run" ] || [ "$2" == "--dry-run" ]; then
    DRY_RUN=true
fi

# Ensure cron scripts exist and are executable
CRON_DIR="$PROJECT_ROOT/scripts/cron"
for script in daily_briefing.sh weekly_ceo_briefing.sh health_check.sh process_needs_action.sh; do
    if [ ! -f "$CRON_DIR/$script" ]; then
        echo -e "${RED}Error: $CRON_DIR/$script not found${NC}"
        echo "Run this from the project root, or check scripts/cron/ directory."
        exit 1
    fi
    chmod +x "$CRON_DIR/$script"
done

# Ensure logs directory exists
mkdir -p "$PROJECT_ROOT/logs"
touch "$PROJECT_ROOT/logs/cron.log"

# Define cron entries
CRON_ENTRIES=$(cat << EOF
# ============================================
# Personal AI Employee - Automated Tasks
# ============================================
# Generated by setup_cron.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Project: $PROJECT_ROOT

# Process Needs_Action every 5 minutes (main automation loop)
*/5 * * * * $CRON_DIR/process_needs_action.sh >> $PROJECT_ROOT/logs/cron.log 2>&1

# Daily Briefing — 8:00 AM every day
0 8 * * * $CRON_DIR/daily_briefing.sh >> $PROJECT_ROOT/logs/cron.log 2>&1

# Weekly CEO Briefing — Monday 7:00 AM
0 7 * * 1 $CRON_DIR/weekly_ceo_briefing.sh >> $PROJECT_ROOT/logs/cron.log 2>&1

# Health Check — every hour
0 * * * * $CRON_DIR/health_check.sh >> $PROJECT_ROOT/logs/cron.log 2>&1
EOF
)

# Handle --remove flag
if [ "$1" == "--remove" ]; then
    echo -e "${YELLOW}Removing AI Employee cron jobs...${NC}"

    if crontab -l 2>/dev/null | grep -q "Personal AI Employee"; then
        crontab -l 2>/dev/null | grep -v "Personal AI Employee" | grep -v "^# ==" | grep -v "^# Generated" | grep -v "^# Project:" | crontab -
        echo -e "${GREEN}✓ AI Employee cron jobs removed${NC}"
    else
        echo -e "${YELLOW}No AI Employee cron jobs found${NC}"
    fi
    exit 0
fi

# Dry-run: just show what would be installed
if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}Dry-run mode — showing cron entries that would be installed:${NC}"
    echo ""
    echo "$CRON_ENTRIES"
    echo ""
    echo -e "${YELLOW}To install, run: ./scripts/setup_cron.sh${NC}"
    exit 0
fi

# Remove any existing AI Employee cron entries
CURRENT_CRONTAB=$(crontab -l 2>/dev/null || echo "")
if echo "$CURRENT_CRONTAB" | grep -q "Personal AI Employee"; then
    echo -e "${YELLOW}Existing AI Employee cron jobs found — removing old entries...${NC}"
    CURRENT_CRONTAB=$(echo "$CURRENT_CRONTAB" | grep -v "Personal AI Employee" | grep -v "^# ==" | grep -v "^# Generated" | grep -v "^# Project:")
fi

# Install new crontab
(
    echo "$CURRENT_CRONTAB"
    echo ""
    echo "$CRON_ENTRIES"
) | crontab -

echo ""
echo -e "${GREEN}✓ Cron jobs installed successfully${NC}"
echo ""
echo "========================================"
echo "  Scheduled Tasks"
echo "========================================"
echo ""
echo -e "${GREEN}Process Needs_Action:${NC}  Every 5 minutes"
echo -e "${GREEN}Daily Briefing:${NC}       8:00 AM every day"
echo -e "${GREEN}Weekly CEO Briefing:${NC}  Monday 7:00 AM"
echo -e "${GREEN}Health Check:${NC}         Every hour"
echo ""
echo "========================================"
echo "  Management"
echo "========================================"
echo ""
echo "View cron jobs:       crontab -l"
echo "Remove cron jobs:     ./scripts/setup_cron.sh --remove"
echo "Dry-run preview:      ./scripts/setup_cron.sh --dry-run"
echo "View cron logs:       tail -f logs/cron.log"
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Scheduling complete!${NC}"
echo -e "${GREEN}========================================${NC}"
